import{a as i}from"./assets/vendor-bdb8a163.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=t(e);fetch(e.href,a)}})();function f({filter:o,page:r,pagination:t,method:n}){const e=Array.from(t.querySelectorAll(".button"));let a=r;e.forEach(s=>{s.addEventListener("click",L=>{s.classList.contains("active")||(a=s.dataset.page,n({filter:o,page:a}),e.forEach(d=>d.classList.remove("active")),s.classList.add("active"))})})}function l({filter:o,page:r,totalPages:t,method:n}){const e=document.querySelector(".pagination");let a="";if(t<=1){e.innerHTML="";return}for(let s=1;s<=t;s++)a+=`
      <button class="button${s===1?" active":""}" data-page="${s}">
        ${s}
      </button>
    `;e.innerHTML=a,f({filter:o,page:r,pagination:e,method:n})}const u={domen:"https://your-energy.b.goit.study/api"};async function g(){const{data:o}=await i({method:"get",url:`${u.domen}/quote`,responseType:"json"});return o}function p(){const o=new Date,r=String(o.getDate()).padStart(2,"0"),t=String(o.getMonth()+1).padStart(2,"0"),n=o.getFullYear();return`${r}/${t}/${n}`}function c(o,r){const t=document.querySelector(".quote .text"),n=document.querySelector(".quote .author");t&&n&&(n.innerHTML=o,t.innerHTML=r)}async function y(){const o=localStorage.getItem("quote"),r=p();if(!o||JSON.parse(o).currentDate!==r){const{author:e,quote:a}=await g();c(e,a),localStorage.setItem("quote",JSON.stringify({currentDate:r,author:e,quote:a}));return}const{author:t,quote:n}=JSON.parse(o);c(t,n)}const m=o=>o.map(({filter:r="Not found",name:t="Not found",imgURL:n})=>`<div class="category-wrap" name="${t}">
      <img class="category-img" src="${n}" alt="${t}">
      <div class="category-text-wrap">
          <p class="category-title">${t}</p>
          <p class="category-subtitle">${r}</p>
      </div>
  </div>`).join("");async function h(o){let r="?";const t=document.querySelector(".content");for(const[e,a]of Object.entries(o))r+=`${e}=${a}&`;const{data:n}=await i({method:"get",url:`${u.domen}/filters${r}limit=12`,responseType:"json"});return t.innerHTML=m(n.results),n.totalPages}async function v(o){const r=Array.from(document.querySelectorAll(".btn-filter"));r.forEach(t=>{t.addEventListener("click",async()=>{if(!t.classList.contains("active")){r.forEach(e=>e.classList.remove("active")),t.classList.add("active");const n=await o({filter:t.dataset.category.replace(" ","+"),page:1});l({filter:t.dataset.category.replace(" ","+"),page:1,totalPages:n,method:o})}})})}document.addEventListener("DOMContentLoaded",async()=>{const o="Muscles",t=h;y(),v(t);const n=await t({filter:o,page:1});l({filter:o,page:1,totalPages:n,method:t})});
//# sourceMappingURL=commonHelpers.js.map
